vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        product:
            uri_prefix: images/product/
            upload_destination: '%kernel.project_dir%/public/images/product'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        service:
            uri_prefix: images/service/
            upload_destination: '%kernel.project_dir%/public/images/service'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
