version: '3'

services: 
  db:
    image: mysql:8.0
    container_name: vparrot-mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: v_parrot
      MYSQL_ROOT_PASSWORD: Increcregym777@
    volumes:
      - db_data:/var/lib/mysql
  
  v_parrot: 
    image: 6f177e59bcf9492767f19fbbbb9be1118de464b170d4db4e88fcb80267925908
    ports:
      - "8080:80"
    env_file:
    - ../.env.local
  
volumes:
  db_data: